name: CashShop
author: DaveTheCamper
version: ${version}
api-version: ${minecraftVersion}
main: me.davethecamper.cashshop.CashShop
commands:
  cash:
    description: Cash commands and in game editor.
  shop:
    description: Player shop acess command.
    aliases: [loja]