name: Release
  uses: mg-smartrent/github-actions-maven-release@v2.6
  with:
    release-branch-name: "master"
    git-release-bot-name: "ReleaseBot"
    git-release-bot-email: "release.bot@smartrent.com"
    access-token: ${GITHUB_TOKEN}

    # Release
    maven-repo-server-id: ${MAVEN_SERVER_ID}
    maven-repo-server-username: ${GITHUB_USERNAME}
    maven-repo-server-password: ${GITHUB_TOKEN}
    maven-release-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"

    # Publish artifacts to GitHub Packages
    maven-publish-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"
    maven-release-publish: "true"
    maven-snapshot-publish: "true"
